version: "3.9"

services:
  api:
    image: ghcr.io/mello2040/consumoenergetico:${TAG:-staging}
    container_name: consumoenergetico-${TAG:-staging}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8081}:8080"      # host:container
    env_file:
      - .env                              # carrega variáveis
    volumes:
      - app_logs:/app/logs
      - app_tmp:/tmp
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  app_logs:
  app_tmp:

networks:
  app_net:
    driver: bridge
