name: CI/CD - Maven + Docker + 2 Ambientes

on:
  push:
    branches: [ "develop", "main" ]   # develop -> staging, main -> prod
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build_test:
    name: Build & Test (Maven)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build + Test
        run: mvn -B -ntp clean verify

  docker_push:
    name: Build & Push Docker
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push (tag por branch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/mello2040/consumoenergetico:${{ github.ref == 'refs/heads/develop' && 'staging' || 'latest' }}

  deploy_staging:
    name: Deploy Staging
    needs: docker_push
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
            cd /srv/consumoenergetico/staging
            docker compose pull
            docker compose up -d
            docker image prune -f

  deploy_production:
    name: Deploy Produção
    needs: docker_push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
            cd /srv/consumoenergetico/prod
            docker compose pull
            docker compose up -d
            docker image prune -f
