name: API BDD Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build (compilar sem testes)
        run: mvn -q -DskipTests package

      - name: Start API (profile test, background)
        run: |
          nohup mvn spring-boot:run "-Dspring-boot.run.profiles=test" > app.log 2>&1 &
          for i in {1..30}; do
            curl -fsS http://localhost:8080/actuator/health || true
            if curl -fsS http://localhost:8080/actuator/health | grep -q UP; then
              echo "API UP"; break
            fi
            sleep 2
          done
          echo "==== APP LOG (últimas linhas) ===="
          tail -n 100 app.log

      - name: Run BDD tests
        run: mvn -DbaseUrl=http://localhost:8080/api -Dtest=RunCucumberTest test

      - name: Publicar relatório do Cucumber
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/cucumber.json
            target/cucumber-report.html
            app.log
